name: Full Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  run-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Setup environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: 01_GitHub/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Run full pipeline
        shell: micromamba-shell {0}
        run: |
          bash 01_GitHub/scripts/00-download-db.sh
          bash 01_GitHub/main.sh

      - name: Upload MultiQC report
        uses: actions/upload-pages-artifact@v3
        with:
          path: 01_GitHub/results/multiqc_report

  deploy:
    needs: run-pipeline
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4